#!/usr/bin/env node
/**
 * Writes the commit being deployed into src/generated/version.ts.
 *
 * Run immediately before `railway up`. That is the only moment the deployed
 * commit is knowable: Railway populates RAILWAY_GIT_COMMIT_SHA only for
 * repo-triggered deploys, and this backend ships from the CLI, so /version
 * answered "unknown" for every deploy this project has ever made.
 *
 * It also records whether the working tree was dirty. `railway up` uploads the
 * working directory, not a commit — so a deploy can carry changes that exist
 * on exactly one machine. Recording that is the difference between "production
 * is running a87fd64" and "production is running something near a87fd64".
 */
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const TARGET = join(HERE, '..', 'src', 'generated', 'version.ts');

const git = (...args) => execFileSync('git', args, { encoding: 'utf8' }).trim();

let sha;
let describe;
let dirty;
try {
  sha = git('rev-parse', 'HEAD');
  describe = git('describe', '--always', '--dirty=-dirty', '--tags');
  dirty = git('status', '--porcelain').length > 0;
} catch (error) {
  console.error('Could not read git state, so the deploy would be unidentifiable:');
  console.error(String(error instanceof Error ? error.message : error));
  process.exit(1);
}

const stampedAt = new Date().toISOString();

const contents = `/**
 * GENERATED by scripts/stamp-version.mjs at deploy time. Do not edit by hand.
 * See that script for why this file exists rather than an env var.
 */
export const BUILD_GIT_SHA = ${JSON.stringify(sha)};
export const BUILD_GIT_DESCRIBE = ${JSON.stringify(describe)};
export const BUILD_TIME = ${JSON.stringify(stampedAt)};
/** False when the deploy did not go through \`npm run deploy\`. */
export const BUILD_STAMPED = true;
/** True when the working tree carried uncommitted changes at stamp time. */
export const BUILD_DIRTY = ${dirty ? 'true' : 'false'};
`;

mkdirSync(dirname(TARGET), { recursive: true });
writeFileSync(TARGET, contents.replace(/\n/g, '\r\n'), 'utf8');

console.log(`stamped ${sha.slice(0, 12)}${dirty ? ' (WORKING TREE DIRTY)' : ''} at ${stampedAt}`);
if (dirty) {
  console.log('');
  console.log('  The working tree has uncommitted changes and `railway up` ships the');
  console.log('  working directory, so production will run code that is on no commit.');
  console.log('  /health will report build.dirty = true so this stays visible.');
}
