-- ============================================
-- Migration 0009: policies reserved for live demos
--
-- The seeded book of business is full of history, which is what makes
-- lookups worth demonstrating. It leaves nowhere to show the claim
-- lifecycle from the start, though, because every policy already has
-- claims attached.
--
-- These three customers each hold one active policy and no claims, so a
-- walkthrough can begin at "file a claim" every time. Re-running this file
-- restores them, but does not delete claims filed against them.
--
-- Generated by database/build-demo-policies.mjs — do not edit by hand.
-- ============================================

INSERT INTO customers (id, full_name, email, phone, date_of_birth, address) VALUES
  ('28d17652-9946-4a26-aa31-d2021fff753e', 'Neel Kapadia', 'neel.kapadia@email.com', '+14155550110', '1992-04-11', '318 Laurel Street, San Mateo, CA 94401'),
  ('358cb70e-5e75-4de3-8315-1d82beefb1aa', 'Sara Dsouza', 'sara.dsouza@email.com', '+14155550111', '1986-09-27', '1204 Sequoia Avenue, Millbrae, CA 94030'),
  ('525d4f21-9641-4480-b420-4fa8c4784f4b', 'Imran Sheikh', 'imran.sheikh@email.com', '+14155550112', '1979-12-02', '77 Hillcrest Road, Daly City, CA 94014')
ON CONFLICT (id) DO NOTHING;

INSERT INTO policies (id, policy_number, customer_id, policy_type, provider, coverage_amount, deductible, premium_monthly, start_date, end_date, status, coverage_details) VALUES
  -- auto — the default choice for a live "file a claim" walkthrough
  ('8d0b220f-5087-433c-b13a-2fae0dcfc825', 'POL-2026-100001', '28d17652-9946-4a26-aa31-d2021fff753e', 'auto', 'SafeGuard Insurance', 55000, 1000, 192, '2026-01-05', '2029-01-05', 'active', '{"vehicle":"2025 Mazda CX-5","vin":"JM3KFBDM1S0412887","liability":"100/300/100","collision":true,"comprehensive":true,"uninsured_motorist":true,"roadside_assistance":true}'::jsonb),
  -- home — for water damage, theft, or fire walkthroughs
  ('885babbb-0f22-4739-964b-1dbb60870c69', 'POL-2026-100002', '358cb70e-5e75-4de3-8315-1d82beefb1aa', 'home', 'SafeGuard Insurance', 410000, 2000, 198, '2026-02-01', '2029-02-01', 'active', '{"property_type":"single_family","square_feet":1620,"year_built":2004,"dwelling_coverage":410000,"personal_property":205000,"liability":300000,"water_damage":true,"theft":true,"flood":false}'::jsonb),
  -- health — for medical claim walkthroughs
  ('e63f0980-2691-4bc2-be13-be11128b6241', 'POL-2026-100003', '525d4f21-9641-4480-b420-4fa8c4784f4b', 'health', 'SafeGuard Insurance', 600000, 2500, 470, '2026-01-15', '2029-01-15', 'active', '{"plan":"PPO","network":"BayCare Plus","out_of_pocket_max":8000,"prescription_coverage":true,"emergency_room":true}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- Reset helper. Run this to clear claims filed against the demo policies and
-- return them to a clean slate before another walkthrough.
--
--   DELETE FROM claims WHERE policy_id IN (
--     SELECT id FROM policies WHERE policy_number IN (
--       'POL-2026-100001',
--       'POL-2026-100002',
--       'POL-2026-100003'
--     )
--   );
