-- ============================================
-- Migration 0026: twenty policies for the refusal and approval batch
--
-- The journey completion run measured how far a good claim gets: ten of ten,
-- every stage. It said nothing about a claim that should not be paid, and a
-- result reporting only approvals invites exactly that question.
--
-- These twenty answer it. Twelve are built to be approvable; eight are built to
-- be refused, and each of the eight trips a DIFFERENT gate.
--
-- Each refusal has its own clean policy, and that is the point of a separate
-- batch rather than reusing the journey twenty. The first refusal run put a
-- case designed to trip 'something_payable' on a policy that already carried a
-- claim of the same type, and it tripped 'no_near_duplicate_claim' instead --
-- the earlier gate wins, so the case was not testing what it said it was.
--
-- The expected gate and verdict for each are recorded in
-- refusal-batch-policies.json, written before the batch was run. A case that
-- trips a different gate is then visibly a different gate, rather than
-- something to be reinterpreted afterwards.
--
-- Generated by database/build-refusal-policies.mjs -- do not edit by hand.
-- Additive and idempotent. Safe to re-run.
-- ============================================

INSERT INTO customers (id, full_name, email, phone, date_of_birth, address) VALUES
  ('11b9482e-afe8-47f5-9ecf-75ab9af151c7', 'Aarav Deshmukh', 'aarav.deshmukh@email.com', '+14155550201', '1988-02-14', '77 Alder Rise, San Mateo, CA 94402'),
  ('3b5336a4-d1b0-45ca-a4cc-23b22fc0b5a1', 'Diya Raghavan', 'diya.raghavan@email.com', '+14155550202', '1993-06-08', '215 Cedar Hollow, Belmont, CA 94002'),
  ('b0bafb3f-8e21-4c08-81c0-2e5dd3e96d83', 'Kabir Sethi', 'kabir.sethi@email.com', '+14155550203', '1985-10-21', '48 Fernhill Court, Millbrae, CA 94030'),
  ('1b612d41-47c8-4352-8211-89ff8aca3f0d', 'Anika Bhatt', 'anika.bhatt@email.com', '+14155550204', '1991-04-30', '1902 Juniper Walk, Foster City, CA 94404'),
  ('cebecd82-9d25-4d90-9839-e2361fb3e894', 'Rehan Malik', 'rehan.malik@email.com', '+14155550205', '1979-08-12', '306 Poplar Bend, San Bruno, CA 94066'),
  ('0f3d0362-50eb-49ee-894b-7cbdc35735ec', 'Saanvi Kulkarni', 'saanvi.kulkarni@email.com', '+14155550206', '1996-01-25', '89 Laurelwood Drive, Burlingame, CA 94010'),
  ('3a9e818a-bd48-41e4-8575-4f05265a46dc', 'Vihaan Chopra', 'vihaan.chopra@email.com', '+14155550207', '1983-11-03', '1140 Birchwood Lane, San Carlos, CA 94070'),
  ('c74b27a3-25d0-484d-9678-d0abb3c4bc1e', 'Myra Fernandes', 'myra.fernandes@email.com', '+14155550208', '1990-07-19', '523 Willowmere Road, Daly City, CA 94015'),
  ('3855c6c8-a1b9-442a-8153-8d9e5245233f', 'Arjun Bakshi', 'arjun.bakshi@email.com', '+14155550209', '1987-03-27', '64 Hazel Grove, Pacifica, CA 94044'),
  ('b54915ed-c0d0-4ed7-98ec-2e33ad20504b', 'Tara Venkatesh', 'tara.venkatesh@email.com', '+14155550210', '1994-09-05', '2210 Maplewood Terrace, Redwood City, CA 94061'),
  ('b107c886-595a-47ea-af03-569d20e48cf3', 'Ishaan Grover', 'ishaan.grover@email.com', '+14155550211', '1981-12-16', '17 Rowan Close, Half Moon Bay, CA 94019'),
  ('d59b8a47-a9ea-41c9-a4da-3976fe4109c1', 'Nyra Sinha', 'nyra.sinha@email.com', '+14155550212', '1997-05-11', '845 Sycamore Point, San Mateo, CA 94403'),
  ('0b0b789f-1446-4f41-85d5-f41add30fa7b', 'Dev Acharya', 'dev.acharya@email.com', '+14155550213', '1986-06-23', '132 Thornbury Way, Belmont, CA 94002'),
  ('ad3109d9-b29f-4165-9bb4-31b02dff76bd', 'Kiara Mehrotra', 'kiara.mehrotra@email.com', '+14155550214', '1992-10-09', '1671 Elmridge Avenue, Millbrae, CA 94030'),
  ('f9884f7f-bc6e-4bad-bc95-e8dc7f00c542', 'Rudra Panicker', 'rudra.panicker@email.com', '+14155550215', '1984-01-18', '95 Ashford Lane, San Bruno, CA 94066'),
  ('145a2d6a-0392-4419-80e7-9a5e6c730455', 'Aisha Kapoor', 'aisha.kapoor@email.com', '+14155550216', '1995-08-26', '408 Brambleton Road, Foster City, CA 94404'),
  ('6671ff99-8cfc-4511-9bfc-9b3436a06cfb', 'Neel Varshney', 'neel.varshney@email.com', '+14155550217', '1989-04-07', '2033 Hollybrook Drive, Burlingame, CA 94010'),
  ('0b7811f4-08d7-4bc2-9e2d-682101b21b63', 'Sara Chandran', 'sara.chandran@email.com', '+14155550218', '1998-02-02', '56 Wren Meadow, San Carlos, CA 94070'),
  ('4ec8c1a9-58a2-4623-a219-9788dfdf2192', 'Yuvan Rastogi', 'yuvan.rastogi@email.com', '+14155550219', '1982-09-29', '1284 Foxglove Street, Pacifica, CA 94044'),
  ('f4dfa6cd-d4a0-4814-a0f0-bb5d989d1718', 'Amara Joshi', 'amara.joshi@email.com', '+14155550220', '1993-12-13', '719 Kestrel Court, Redwood City, CA 94065')
ON CONFLICT (id) DO NOTHING;

-- --- The twelve built to be approvable ------------------------------------

INSERT INTO policies (id, policy_number, customer_id, policy_type, provider, coverage_amount, deductible, premium_monthly, start_date, end_date, status, coverage_details) VALUES
  -- POL-2026-400001  approvable: collision of 28,000 leaves 27,000 payable
  ('8f4e89ad-a029-4752-bb96-b46fb1de1f56', 'POL-2026-400001', '11b9482e-afe8-47f5-9ecf-75ab9af151c7', 'auto', 'SafeGuard Insurance', 780000, 1000, 1380, '2024-08-29', '2028-08-29', 'active', '{"vehicle":"2025 Hyundai Verna SX","registration":"MH12 AB 1122","idv":780000,"cover":"comprehensive","own_damage":true,"third_party_liability":1500000,"zero_depreciation":true,"roadside_assistance":true}'::jsonb),
  -- POL-2026-400002  approvable: windshield of 12,800 leaves 11,800 payable
  ('d5fe2ab5-bace-4977-b0e0-b415cfb3ed2e', 'POL-2026-400002', '3b5336a4-d1b0-45ca-a4cc-23b22fc0b5a1', 'auto', 'SafeGuard Insurance', 640000, 1000, 1210, '2024-08-29', '2028-08-29', 'active', '{"vehicle":"2024 Honda Amaze VX","registration":"KA03 CD 3344","idv":640000,"cover":"comprehensive","own_damage":true,"third_party_liability":1500000,"zero_depreciation":true,"roadside_assistance":true}'::jsonb),
  -- POL-2026-400003  approvable: theft of 44,000 leaves 42,000 payable
  ('fe827333-f270-4c8a-8157-130482b0a76d', 'POL-2026-400003', 'b0bafb3f-8e21-4c08-81c0-2e5dd3e96d83', 'auto', 'SafeGuard Insurance', 1120000, 2000, 1980, '2024-08-29', '2028-08-29', 'active', '{"vehicle":"2026 Toyota Hyryder","registration":"DL3C EF 5566","idv":1120000,"cover":"comprehensive","own_damage":true,"third_party_liability":1500000,"zero_depreciation":true,"roadside_assistance":true}'::jsonb),
  -- POL-2026-400004  approvable: vandalism of 15,600 leaves 14,600 payable
  ('549f3349-8b83-4c33-af9d-c61472c466ff', 'POL-2026-400004', '1b612d41-47c8-4352-8211-89ff8aca3f0d', 'auto', 'SafeGuard Insurance', 520000, 1000, 1020, '2024-08-29', '2028-08-29', 'active', '{"vehicle":"2023 Maruti Swift ZXi","registration":"GJ05 GH 7788","idv":520000,"cover":"comprehensive","own_damage":true,"third_party_liability":1500000,"zero_depreciation":true,"roadside_assistance":true}'::jsonb),
  -- POL-2026-400005  approvable: comprehensive of 36,000 leaves 34,000 payable
  ('b0ee7e6b-6d0c-4e0d-b137-aaaa7888ab4c', 'POL-2026-400005', 'cebecd82-9d25-4d90-9839-e2361fb3e894', 'auto', 'SafeGuard Insurance', 890000, 2000, 1560, '2024-08-29', '2028-08-29', 'active', '{"vehicle":"2025 Kia Sonet HTX","registration":"TN22 IJ 9900","idv":890000,"cover":"comprehensive","own_damage":true,"third_party_liability":1500000,"zero_depreciation":true,"roadside_assistance":true}'::jsonb),
  -- POL-2026-400006  approvable: collision of 19,400 leaves 18,400 payable
  ('685d23b2-ae7f-47f4-bc19-1558823ee386', 'POL-2026-400006', '0f3d0362-50eb-49ee-894b-7cbdc35735ec', 'auto', 'SafeGuard Insurance', 710000, 1000, 1290, '2024-08-29', '2028-08-29', 'active', '{"vehicle":"2024 Tata Punch Accomplished","registration":"MH14 KL 2233","idv":710000,"cover":"comprehensive","own_damage":true,"third_party_liability":1500000,"zero_depreciation":true,"roadside_assistance":true}'::jsonb),
  -- POL-2026-400007  approvable: water_damage of 37,500 leaves 32,500 payable
  ('0eefa542-da6e-432d-b96c-ee18ad7bc667', 'POL-2026-400007', '3a9e818a-bd48-41e4-8575-4f05265a46dc', 'home', 'SafeGuard Insurance', 2650000, 5000, 860, '2024-08-29', '2028-08-29', 'active', '{"property_type":"apartment","square_feet":1620,"year_built":2007,"structure_cover":2650000,"contents_cover":662500,"public_liability":500000,"water_damage":true,"burglary":true,"earthquake":true,"flood":false}'::jsonb),
  -- POL-2026-400008  approvable: fire_damage of 48,000 leaves 43,000 payable
  ('12b0decf-50d5-4b9b-935a-c6a7f1c18b9d', 'POL-2026-400008', 'c74b27a3-25d0-484d-9678-d0abb3c4bc1e', 'home', 'SafeGuard Insurance', 1880000, 5000, 700, '2024-08-29', '2028-08-29', 'active', '{"property_type":"apartment","square_feet":1380,"year_built":1999,"structure_cover":1880000,"contents_cover":470000,"public_liability":500000,"water_damage":true,"burglary":true,"earthquake":true,"flood":false}'::jsonb),
  -- POL-2026-400009  approvable: storm_damage of 34,800 leaves 24,800 payable
  ('0a57d3a0-b61b-435b-9043-198e64b54ad1', 'POL-2026-400009', '3855c6c8-a1b9-442a-8153-8d9e5245233f', 'home', 'SafeGuard Insurance', 3400000, 10000, 1190, '2024-08-29', '2028-08-29', 'active', '{"property_type":"apartment","square_feet":1810,"year_built":2013,"structure_cover":3400000,"contents_cover":850000,"public_liability":500000,"water_damage":true,"burglary":true,"earthquake":true,"flood":false}'::jsonb),
  -- POL-2026-400010  approvable: theft of 21,600 leaves 16,600 payable
  ('f0b2fe4b-b191-4399-8fda-a9161edfcd8c', 'POL-2026-400010', 'b54915ed-c0d0-4ed7-98ec-2e33ad20504b', 'home', 'SafeGuard Insurance', 1460000, 5000, 620, '2024-08-29', '2028-08-29', 'active', '{"property_type":"apartment","square_feet":1250,"year_built":1996,"structure_cover":1460000,"contents_cover":365000,"public_liability":500000,"water_damage":true,"burglary":true,"earthquake":true,"flood":false}'::jsonb),
  -- POL-2026-400011  approvable: medical of 43,000 leaves 38,000 payable
  ('c93c1534-fb75-4151-9bd8-6a4322b34d73', 'POL-2026-400011', 'b107c886-595a-47ea-af03-569d20e48cf3', 'health', 'SafeGuard Health', 950000, 5000, 2380, '2024-08-29', '2028-08-29', 'active', '{"plan":"Family Floater","network":"BayCare Plus","room_rent_limit":7500,"copay_percent":0,"pre_existing_waiting_months":36,"day_care_procedures":true,"prescription_coverage":true,"emergency_room":true}'::jsonb),
  -- POL-2026-400012  approvable: hospitalisation of 38,500 leaves 33,500 payable
  ('c5bf7486-f1e1-4052-ae13-6c9a76fbb3c5', 'POL-2026-400012', 'd59b8a47-a9ea-41c9-a4da-3976fe4109c1', 'health', 'SafeGuard Health', 680000, 5000, 1820, '2024-08-29', '2028-08-29', 'active', '{"plan":"Individual","network":"Peninsula Health","room_rent_limit":5000,"copay_percent":0,"pre_existing_waiting_months":36,"day_care_procedures":true,"prescription_coverage":true,"emergency_room":true}'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- --- The eight built to be refused, one gate each --------------------------

INSERT INTO policies (id, policy_number, customer_id, policy_type, provider, coverage_amount, deductible, premium_monthly, start_date, end_date, status, coverage_details) VALUES
  -- POL-2026-400013  refusal: expects deny at policy_in_force_on_incident_date
  --   The incident predates the policy term. A date comparison, not a judgement.
  ('d464daca-267f-4069-96e8-3399892589c2', 'POL-2026-400013', '0b0b789f-1446-4f41-85d5-f41add30fa7b', 'auto', 'SafeGuard Insurance', 700000, 1000, 1300, '2024-08-29', '2028-08-29', 'active', '{"vehicle":"2024 Skoda Slavia","registration":"MH01 MN 4455","idv":700000,"cover":"comprehensive","own_damage":true,"third_party_liability":1500000,"zero_depreciation":true,"roadside_assistance":true}'::jsonb),
  -- POL-2026-400014  refusal: expects deny at claim_type_covered
  --   A medical claim on a motor policy. Outside the schedule, so the refusal is a matter of record.
  ('a3cc83bb-bc15-4403-aa2f-7af0d6cfd9d6', 'POL-2026-400014', 'ad3109d9-b29f-4165-9bb4-31b02dff76bd', 'auto', 'SafeGuard Insurance', 660000, 1000, 1240, '2024-08-29', '2028-08-29', 'active', '{"vehicle":"2024 Nissan Magnite","registration":"KA51 OP 6677","idv":660000,"cover":"comprehensive","own_damage":true,"third_party_liability":1500000,"zero_depreciation":true,"roadside_assistance":true}'::jsonb),
  -- POL-2026-400015  refusal: expects deny at something_payable
  --   The claim is smaller than the excess. Nothing is payable and the arithmetic says so.
  ('ae05e661-6bf6-461c-bf7f-d82a1d54dc11', 'POL-2026-400015', 'f9884f7f-bc6e-4bad-bc95-e8dc7f00c542', 'auto', 'SafeGuard Insurance', 540000, 2000, 1080, '2024-08-29', '2028-08-29', 'active', '{"vehicle":"2023 Renault Triber","registration":"RJ14 QR 8899","idv":540000,"cover":"comprehensive","own_damage":true,"third_party_liability":1500000,"zero_depreciation":true,"roadside_assistance":true}'::jsonb),
  -- POL-2026-400016  refusal: expects escalate at claimed_amount_within_coverage
  --   Above the sum insured. Escalates rather than denies: what this needs is somebody telling the claimant.
  ('834c7c81-467a-41fb-8f72-2b5ac97dcf15', 'POL-2026-400016', '145a2d6a-0392-4419-80e7-9a5e6c730455', 'auto', 'SafeGuard Insurance', 820000, 1000, 1450, '2024-08-29', '2028-08-29', 'active', '{"vehicle":"2025 MG Astor Sharp","registration":"TS09 ST 1010","idv":820000,"cover":"comprehensive","own_damage":true,"third_party_liability":1500000,"zero_depreciation":true,"roadside_assistance":true}'::jsonb),
  -- POL-2026-400017  refusal: expects escalate at no_near_duplicate_claim
  --   Filed twice within the seven-day window. Possibly one incident claimed twice, possibly two; the system refuses to decide that itself.
  ('c421b21e-c298-452a-97d3-ea68f32e358a', 'POL-2026-400017', '6671ff99-8cfc-4511-9bfc-9b3436a06cfb', 'home', 'SafeGuard Insurance', 2100000, 5000, 790, '2024-08-29', '2028-08-29', 'active', '{"property_type":"apartment","square_feet":1490,"year_built":2002,"structure_cover":2100000,"contents_cover":525000,"public_liability":500000,"water_damage":true,"burglary":true,"earthquake":true,"flood":false}'::jsonb),
  -- POL-2026-400018  refusal: expects escalate at claimed_amount_stated
  --   No amount stated, so there is nothing to assess. Escalates rather than guessing on the claimant's behalf.
  ('e27c8de0-30d7-4e75-83fa-e1f66e9ef6e5', 'POL-2026-400018', '0b7811f4-08d7-4bc2-9e2d-682101b21b63', 'home', 'SafeGuard Insurance', 1740000, 5000, 680, '2024-08-29', '2028-08-29', 'active', '{"property_type":"apartment","square_feet":1310,"year_built":1998,"structure_cover":1740000,"contents_cover":435000,"public_liability":500000,"water_damage":true,"burglary":true,"earthquake":true,"flood":false}'::jsonb),
  -- POL-2026-400019  refusal: expects refused_at_intake at INTAKE:policy_not_active
  --   A cancelled policy. file-claim refuses before a row is written; the adjudication gate is never reached.
  ('32b07a2e-80d2-4e92-9424-61607f061882', 'POL-2026-400019', '4ec8c1a9-58a2-4623-a219-9788dfdf2192', 'auto', 'SafeGuard Insurance', 590000, 1000, 1120, '2024-08-29', '2028-08-29', 'cancelled', '{"vehicle":"2022 Ford EcoSport Titanium","registration":"MH04 UV 1212","idv":590000,"cover":"comprehensive","own_damage":true,"third_party_liability":1500000,"zero_depreciation":true,"roadside_assistance":true}'::jsonb),
  -- POL-2026-400020  refusal: expects refused_at_intake at INTAKE:policy_not_active
  --   A lapsed policy, unrenewed. Same intake refusal, and the renewal path is what answers it.
  ('5de79d79-6ab2-4b5e-82c2-7195e6748a00', 'POL-2026-400020', 'f4dfa6cd-d4a0-4814-a0f0-bb5d989d1718', 'health', 'SafeGuard Health', 720000, 5000, 1900, '2024-08-29', '2026-07-30', 'expired', '{"plan":"Individual","network":"Coastside Network","room_rent_limit":6000,"copay_percent":0,"pre_existing_waiting_months":36,"day_care_procedures":true,"prescription_coverage":true,"emergency_room":true}'::jsonb)
ON CONFLICT (id) DO NOTHING;
